Repository JasonCostanza/Dice-Vault, pull requests merged in 2024-04, with the labels that each got.

#27 improve sort list
  vault.css
  vault.html
  vault.js
Labels: bug

#35 Update Feature Request template
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#36 Handle Critical Hit Styles
  scripts/diceCrits.js
  scripts/vault.js
  vault.html
Labels: enhancement
